# Generated by Django 3.0.8 on 2020-08-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200809_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='snippet',
            field=models.CharField(default='lorem ipsums', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(max_length=200),
        ),
    ]
