# Generated by Django 3.0.8 on 2020-08-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200809_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_im',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
