# Generated by Django 3.0.8 on 2020-08-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article_post_im'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='post_im',
            new_name='image',
        ),
    ]
