# Generated by Django 3.0.8 on 2020-08-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200813_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='disp_pic',
            field=models.FileField(blank=True, default='images/profile/default_dp_nb.png', null=True, upload_to='images/profile/'),
        ),
    ]
