# Generated by Django 3.0.8 on 2020-08-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200814_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
