# Generated by Django 3.0.8 on 2020-08-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_photos_caption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='field',
            new_name='profession',
        ),
    ]
