# Generated by Django 3.0.8 on 2020-08-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200815_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linked_in',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
