# Generated by Django 3.0.8 on 2020-08-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200815_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postupdate',
            name='post',
            field=models.TextField(blank=True, null=True),
        ),
    ]
