# Generated by Django 3.0.8 on 2020-08-20 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200817_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
